language: android
dist: trusty
branches:
  only:
  - prod
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_ea1c432b0be8_key -iv $encrypted_ea1c432b0be8_iv -in secrets.tar.enc -out secrets.tar -d
- tar xzvf secrets.tar
- chmod +x gradlew
script:
- ./gradlew publishBundle
