language: android
dist: trusty
branches:
  only:
  - prod
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
  - openssl aes-256-cbc -K $encrypted_897d929f3880_key -iv $encrypted_897d929f3880_iv -in google-services.json.enc -out app/google-services.json -d
  - chmod +x gradlew
